

export const editors = [
  {
    id: "1",
    name: "Sarah Johnson",
    title: "Senior Video Editor & Motion Designer",
    avatar: "/placeholder.svg?height=100&width=100",
    rating: 4.9,
    reviews: 127,
    hourlyRate: 85,
    skills: ["Adobe Premiere Pro", "After Effects", "DaVinci Resolve", "Motion Graphics"],
    availability: "Available Now",
    portfolio: ["/placeholder.svg?height=300&width=400"],
    verified: true,
    featured: true,
    location: "New York, USA",
    languages: ["English", "Spanish"],
  },
  {
    id: "2",
    name: "Michael Chen",
    title: "Video Editor & Color Grading Specialist",
    avatar: "/placeholder.svg?height=100&width=100",
    rating: 4.8,
    reviews: 93,
    hourlyRate: 75,
    skills: ["Final Cut Pro", "DaVinci Resolve", "Color Grading", "Sound Design"],
    availability: "Available in 3 days",
    portfolio: ["/placeholder.svg?height=300&width=400"],
    verified: true,
    featured: false,
    location: "Toronto, Canada",
    languages: ["English", "Chinese"],
  },
  {
    id: "3",
    name: "Emma Wilson",
    title: "Creative Video Editor & VFX Artist",
    avatar: "/placeholder.svg?height=100&width=100",
    rating: 4.7,
    reviews: 78,
    hourlyRate: 95,
    skills: ["Adobe Premiere Pro", "After Effects", "Nuke", "3D Animation"],
    availability: "Available Now",
    portfolio: ["/placeholder.svg?height=300&width=400"],
    verified: true,
    featured: true,
    location: "London, UK",
    languages: ["English", "French"],
  },
]

